"""Tests for dependency-list resolution (lockfile detection / requirements.txt reference)."""

from __future__ import annotations

import dataclasses
from pathlib import Path

import pytest

from pyappdist.deps import (
    _add_encoded_artifact_names,
    _auto_detect,
    _ensure_packages_key,
    _export_cmd,
    resolve_manager,
    resolve_requirements,
)
from pyappdist.errors import BuildError


def _touch(d: Path, name: str) -> None:
    (d / name).write_text("", encoding="utf-8")


def test_auto_detect_none(tmp_path: Path):
    assert _auto_detect(tmp_path) is None


@pytest.mark.parametrize(
    "lockfile,expected",
    [("uv.lock", "uv"), ("poetry.lock", "poetry"), ("Pipfile.lock", "pipenv"), ("pdm.lock", "pdm")],
)
def test_auto_detect_single(tmp_path: Path, lockfile: str, expected: str):
    _touch(tmp_path, lockfile)
    assert _auto_detect(tmp_path) == expected


def test_auto_detect_priority(tmp_path: Path):
    # When several exist, first wins in the order uv -> poetry -> pipenv -> pdm.
    _touch(tmp_path, "poetry.lock")
    _touch(tmp_path, "pdm.lock")
    _touch(tmp_path, "uv.lock")
    assert _auto_detect(tmp_path) == "uv"


def test_resolve_manager_override_wins(tmp_path: Path):
    _touch(tmp_path, "uv.lock")
    assert resolve_manager(tmp_path, "pdm", log=lambda _m: None) == "pdm"


def test_resolve_manager_auto(tmp_path: Path):
    _touch(tmp_path, "poetry.lock")
    assert resolve_manager(tmp_path, None, log=lambda _m: None) == "poetry"


def test_resolve_manager_fallback_to_requirements_txt(tmp_path: Path):
    # No lockfile, no manager setting, but a checked-in requirements.txt: use it (with a warning).
    _touch(tmp_path, "requirements.txt")
    msgs: list[str] = []
    assert resolve_manager(tmp_path, None, log=msgs.append) == "requirements.txt"
    assert any("warning" in m for m in msgs)


def test_resolve_manager_undeterminable_errors(tmp_path: Path):
    # No manager setting, no lockfile, and no requirements.txt: fail at determination time.
    with pytest.raises(BuildError, match="cannot determine the dependency manager"):
        resolve_manager(tmp_path, None, log=lambda _m: None)


def test_export_cmd_no_extras_is_nodev_default():
    # No extras: the command is the base export (production deps only).
    # uv exports PEP 751 pylock.toml so per-package index pins survive.
    assert _export_cmd("uv", ()) == [
        "uv", "export", "--frozen", "--no-dev", "--no-emit-project",
        "--format", "pylock.toml",
    ]


@pytest.mark.parametrize(
    "manager,flag",
    [("uv", "--extra"), ("poetry", "--extras"), ("pdm", "--group")],
)
def test_export_cmd_appends_extra_flags(manager: str, flag: str):
    cmd = _export_cmd(manager, ("gui", "extra"))
    # Each extra becomes a repeated selector flag, in order, after the base command.
    assert cmd[-4:] == [flag, "gui", flag, "extra"]


def test_export_cmd_pipenv_joins_categories():
    # pipenv's --categories is a single comma-separated option, and naming any
    # category replaces the default "packages" — so it must appear exactly once,
    # with "packages" listed first to keep production deps in the export.
    cmd = _export_cmd("pipenv", ("gui", "extra"))
    assert cmd == ["pipenv", "requirements", "--hash", "--categories", "packages,gui,extra"]


def test_export_cmd_pipenv_no_extras_has_no_categories_flag():
    # Without extras the default export (packages only) is already correct.
    assert _export_cmd("pipenv", ()) == ["pipenv", "requirements", "--hash"]


def test_add_encoded_artifact_names_adds_decoded_name():
    # A %2B (encoded "+") in the URL basename gets an explicit decoded name,
    # so pip's URL-derived filename validation is bypassed; the URL is untouched.
    line = (
        '    { url = "https://dl.example/whl/torch-2.12.1%2Bcu130-cp312-win_amd64.whl",'
        ' hashes = { sha256 = "aa" } },\n'
    )
    fixed = _add_encoded_artifact_names(line)
    assert 'name = "torch-2.12.1+cu130-cp312-win_amd64.whl", url =' in fixed
    assert "torch-2.12.1%2Bcu130-cp312-win_amd64.whl" in fixed  # URL preserved


def test_add_encoded_artifact_names_leaves_plain_urls_alone():
    text = (
        'wheels = [\n'
        '    { url = "https://files.pythonhosted.org/x/numpy-2.4.6-cp312-any.whl",'
        ' hashes = { sha256 = "bb" } },\n'
        ']\n'
    )
    assert _add_encoded_artifact_names(text) == text


def test_ensure_packages_key_appends_when_missing():
    # uv omits `packages` entirely for a no-dependency project; append an empty array.
    pylock = (
        "# This file was autogenerated by uv\n"
        'lock-version = "1.0"\n'
        'created-by = "uv"\n'
        'requires-python = ">=3.11"\n'
    )
    fixed = _ensure_packages_key(pylock)
    assert fixed == pylock + "packages = []\n"


def test_ensure_packages_key_appends_newline_when_missing():
    assert _ensure_packages_key('lock-version = "1.0"') == 'lock-version = "1.0"\npackages = []\n'


def test_ensure_packages_key_leaves_array_of_tables_alone():
    pylock = 'lock-version = "1.0"\n\n[[packages]]\nname = "requests"\n'
    assert _ensure_packages_key(pylock) == pylock


def test_ensure_packages_key_leaves_inline_array_alone():
    pylock = 'lock-version = "1.0"\npackages = []\n'
    assert _ensure_packages_key(pylock) == pylock


def _fake_export(monkeypatch, stdout: str) -> None:
    """Replace subprocess.run in deps with a successful fake export."""
    import subprocess as _subprocess

    def fake_run(cmd, **_kwargs):
        return _subprocess.CompletedProcess(cmd, 0, stdout=stdout, stderr="")

    monkeypatch.setattr("pyappdist.deps.subprocess.run", fake_run)


def test_resolve_requirements_uv_writes_pylock(tmp_path: Path, sample_config, monkeypatch):
    # uv manager: the export is PEP 751 pylock.toml (per-package index pins survive)
    # and must land under pip's recognized file name.
    project = tmp_path / "proj"
    project.mkdir()
    _touch(project, "uv.lock")
    wheelhouse = tmp_path / "wh"
    wheelhouse.mkdir()
    cfg = dataclasses.replace(sample_config, project_dir=project, manager=None)
    _fake_export(monkeypatch, 'lock-version = "1.0"\n')

    out = resolve_requirements(cfg, wheelhouse, log=lambda _m: None)

    assert out == wheelhouse / "pylock.toml"
    # A no-dependency export gets a spec-required empty ``packages`` appended.
    assert out.read_text(encoding="utf-8") == 'lock-version = "1.0"\npackages = []\n'


def test_resolve_requirements_poetry_writes_requirements_txt(tmp_path: Path, sample_config, monkeypatch):
    # Non-uv managers keep the requirements.txt export.
    project = tmp_path / "proj"
    project.mkdir()
    _touch(project, "poetry.lock")
    wheelhouse = tmp_path / "wh"
    wheelhouse.mkdir()
    cfg = dataclasses.replace(sample_config, project_dir=project, manager=None)
    _fake_export(monkeypatch, "requests==2.0\n")

    out = resolve_requirements(cfg, wheelhouse, log=lambda _m: None)

    assert out == wheelhouse / "requirements.txt"
    assert out.read_text(encoding="utf-8") == "requests==2.0\n"


def test_resolve_requirements_extras_ignored_for_requirements_txt(tmp_path: Path, sample_config):
    project = tmp_path / "proj"
    project.mkdir()
    (project / "requirements.txt").write_text("requests==2.0\n", encoding="utf-8")
    wheelhouse = tmp_path / "wh"
    wheelhouse.mkdir()
    cfg = dataclasses.replace(
        sample_config, project_dir=project, manager="requirements.txt", extras=("gui",)
    )
    msgs: list[str] = []

    resolve_requirements(cfg, wheelhouse, log=msgs.append)

    assert any("ignoring targets.extras" in m for m in msgs)


def test_resolve_requirements_uses_existing_file(tmp_path: Path, sample_config):
    project = tmp_path / "proj"
    project.mkdir()
    (project / "requirements.txt").write_text("requests==2.0\n", encoding="utf-8")
    wheelhouse = tmp_path / "wh"
    wheelhouse.mkdir()
    cfg = dataclasses.replace(sample_config, project_dir=project, manager="requirements.txt")

    out = resolve_requirements(cfg, wheelhouse, log=lambda _m: None)

    assert out == wheelhouse / "requirements.txt"
    assert out.read_text(encoding="utf-8") == "requests==2.0\n"


def test_resolve_requirements_missing_file_errors(tmp_path: Path, sample_config):
    project = tmp_path / "proj"
    project.mkdir()
    wheelhouse = tmp_path / "wh"
    wheelhouse.mkdir()
    cfg = dataclasses.replace(sample_config, project_dir=project, manager="requirements.txt")

    with pytest.raises(BuildError, match="requirements.txt"):
        resolve_requirements(cfg, wheelhouse, log=lambda _m: None)
