# ---------------------------------------------------------------------------
# Static installer logic (generated by pyappdist; do not edit by hand).
#
# The lines above this block define:
#   APP_NAME DIST_NAME VERSION DESKTOP CATEGORIES LAUNCHERS DECOMPRESS PAYLOAD_SHA256 SELF
# LAUNCHERS is a newline-separated list of "name:gui:icon:title" records, where
# gui is 1/0, icon is the bundled icon filename (empty = no desktop entry), and
# title is the display title for the .desktop Name (empty = default naming).
# One record per line (never whitespace-separated): a launcher name may contain
# spaces, so every loop below reads it with `while IFS= read -r` over a here-doc
# (a here-doc, not a pipeline, so the loop body runs in the current shell).
# The fields themselves never contain ":" (the config rejects it in names and
# titles, and the icon filename derives from the name).
# DESKTOP is 1 on Linux (write freedesktop .desktop entries) and 0 on macOS,
# which has no freedesktop equivalent (symlinks only). DECOMPRESS is the filter
# that turns the payload back into a tar stream (e.g. "xz -dc"); PAYLOAD_SHA256
# is the expected checksum of the appended payload.
#
# A compressed tar of the image tree is appended after the marker line (see the
# awk pattern below) at the very end of this file.
# ---------------------------------------------------------------------------

PREFIX="${PREFIX:-$HOME/.local}"
DO_UNINSTALL=0

print_help() {
    cat <<EOF
$APP_NAME $VERSION installer

Usage: $0 [options]
  --prefix DIR    install prefix (default: \$HOME/.local)
  --uninstall     remove a previous installation
  -h, --help      show this help
EOF
}

while [ $# -gt 0 ]; do
    case "$1" in
        --prefix) PREFIX="$2"; shift 2 ;;
        --prefix=*) PREFIX="${1#--prefix=}"; shift ;;
        --uninstall) DO_UNINSTALL=1; shift ;;
        -h|--help) print_help; exit 0 ;;
        *) echo "error: unknown option: $1" >&2; exit 2 ;;
    esac
done

# Canonicalize PREFIX to an absolute path before deriving any paths from it:
# symlink targets resolve relative to the symlink's own directory, and the
# .desktop Exec= lines and the generated uninstall.sh bake the paths in
# verbatim, so a relative prefix would produce dangling links and an
# uninstaller that only works from the original directory.
if [ "$DO_UNINSTALL" = "0" ]; then
    mkdir -p "$PREFIX"
fi
if _abs_prefix=$(CDPATH= cd -- "$PREFIX" 2>/dev/null && pwd); then
    PREFIX=$_abs_prefix
else
    echo "error: cannot resolve install prefix: $PREFIX" >&2
    exit 1
fi

LIBDIR="$PREFIX/lib/$DIST_NAME"
BINDIR="$PREFIX/bin"
APPDIR="${XDG_DATA_HOME:-$HOME/.local/share}/applications"

# Count the launchers that get a .desktop entry; with more than one, each entry's
# Name is suffixed with the launcher name so the menu entries are distinguishable
# (mirrors the MSIX manifest's DisplayName handling).
_desktop_entries=0
if [ "$DESKTOP" = "1" ]; then
    while IFS= read -r _entry; do
        [ -n "$_entry" ] || continue
        _icon=${_entry#*:}
        _icon=${_icon#*:}
        _icon=${_icon%%:*}
        if [ -n "$_icon" ]; then _desktop_entries=$((_desktop_entries + 1)); fi
    done <<EOF
$LAUNCHERS
EOF
fi

# A Desktop Entry value ends at the newline, and a tab cannot appear literally
# either, so a prefix containing one cannot be represented — refuse up front
# rather than write a corrupt entry. Everything else is escaped (see below).
# Checked only when an entry will actually be written, and never on uninstall.
if [ "$DO_UNINSTALL" = "0" ] && [ "$_desktop_entries" -gt 0 ] &&
   [ "$(printf '%s' "$PREFIX" | tr -d '\n\t')" != "$PREFIX" ]; then
    echo "error: the install prefix contains a tab or newline, which cannot be" >&2
    echo "       written to a .desktop entry: $PREFIX" >&2
    exit 1
fi

# Single-quote a value for safe embedding in the generated uninstall.sh, so
# $, backticks, or quotes in the install paths stay literal at uninstall time.
sq() {
    printf "'%s'" "$(printf '%s' "$1" | sed "s/'/'\\\\''/g")"
}

# Escape a value for a Desktop Entry field of type "string": the spec reserves
# the backslash, so a literal one must be doubled. Applied to every generated
# value, since the install prefix is arbitrary user input.
desktop_string() {
    printf '%s' "$1" | sed 's/\\/\\\\/g'
}

# Escape a path as one quoted argument of an Exec= value. Two passes, because
# Exec values are escaped twice by the spec: inside the quotes a literal ", `,
# $ or \ takes a backslash (the Exec reserved characters), and the resulting
# value then goes through the string escaping above.
desktop_exec_arg() {
    printf '"%s"' "$(printf '%s' "$1" | sed -e 's/[\\`$"]/\\&/g' -e 's/\\/\\\\/g')"
}

refresh_desktop_db() {
    if command -v update-desktop-database >/dev/null 2>&1; then
        update-desktop-database "$APPDIR" >/dev/null 2>&1 || true
    fi
}

# Compute the SHA-256 of stdin, printing just the hex digest. Tries the common
# tools in turn; prints nothing if none is available (caller treats that as
# "cannot verify" rather than a failure). shasum covers macOS, sha256sum Linux.
sha256_of_stdin() {
    if command -v sha256sum >/dev/null 2>&1; then
        sha256sum | cut -d' ' -f1
    elif command -v shasum >/dev/null 2>&1; then
        shasum -a 256 | cut -d' ' -f1
    elif command -v openssl >/dev/null 2>&1; then
        openssl dgst -sha256 | sed 's/.*= *//'
    fi
}

# Remove a previous install. The previous version's uninstall.sh records the
# launcher set that was actually installed — which can differ from this
# package's $LAUNCHERS after a rename or removal — so run it first when
# present; the loop below then covers installs that have no uninstall.sh.
remove_install() {
    if [ -f "$LIBDIR/uninstall.sh" ]; then
        sh "$LIBDIR/uninstall.sh" >/dev/null 2>&1 || true
    fi
    while IFS= read -r _entry; do
        [ -n "$_entry" ] || continue
        _name=${_entry%%:*}
        _rest=${_entry#*:}
        _icon=${_rest#*:}
        _icon=${_icon%%:*}
        rm -f "$BINDIR/$_name"
        if [ "$DESKTOP" = "1" ] && [ -n "$_icon" ]; then
            rm -f "$APPDIR/$DIST_NAME-$_name.desktop"
        fi
    done <<EOF
$LAUNCHERS
EOF
    rm -rf "$LIBDIR"
    [ "$DESKTOP" = "1" ] && refresh_desktop_db
}

if [ "$DO_UNINSTALL" = "1" ]; then
    if [ ! -d "$LIBDIR" ]; then
        echo "error: $APP_NAME is not installed at $LIBDIR" >&2
        exit 1
    fi
    remove_install
    echo "Uninstalled $APP_NAME from $PREFIX"
    exit 0
fi

echo "Installing $APP_NAME $VERSION -> $LIBDIR"

# Locate the appended payload (the compressed tar after the marker line).
_payload_line=$(awk '/^__PYAPPDIST_PAYLOAD__$/ { print NR + 1; exit }' "$SELF")
if [ -z "$_payload_line" ]; then
    echo "error: payload marker not found in $SELF" >&2
    exit 1
fi

# Check the tools extraction needs *before* removing any existing install, so a
# missing decompressor (e.g. xz on a minimal system) can't leave the user with nothing.
for _tool in "${DECOMPRESS%% *}" tar; do
    if ! command -v "$_tool" >/dev/null 2>&1; then
        echo "error: required tool '$_tool' not found; cannot extract the payload" >&2
        exit 1
    fi
done

# Verify the payload checksum *before* removing any existing install, so a
# corrupted download can't leave the user with nothing.
_actual_sha=$(tail -n +"$_payload_line" "$SELF" | sha256_of_stdin)
if [ -z "$_actual_sha" ]; then
    echo "note: no sha256 tool found; skipping integrity check" >&2
elif [ "$_actual_sha" != "$PAYLOAD_SHA256" ]; then
    echo "error: payload checksum mismatch (file is corrupt or truncated)" >&2
    echo "  expected $PAYLOAD_SHA256" >&2
    echo "  actual   $_actual_sha" >&2
    exit 1
fi

remove_install            # clean any previous version (upgrade in place)
mkdir -p "$LIBDIR" "$BINDIR"

if ! tail -n +"$_payload_line" "$SELF" | $DECOMPRESS | tar xf - -C "$LIBDIR"; then
    echo "error: failed to extract payload" >&2
    exit 1
fi

# Symlink each launcher onto PATH and (on Linux, when it has an icon) register a .desktop.
_installed_cmds=""
while IFS= read -r _entry; do
    [ -n "$_entry" ] || continue
    _name=${_entry%%:*}
    _rest=${_entry#*:}
    _gui=${_rest%%:*}
    _rest=${_rest#*:}
    _icon=${_rest%%:*}
    _title=${_rest#*:}
    ln -sf "$LIBDIR/$_name" "$BINDIR/$_name"
    # Newline-separated, like LAUNCHERS itself, so a name with spaces stays one entry.
    _installed_cmds="$_installed_cmds
$_name"
    if [ "$DESKTOP" = "1" ] && [ -n "$_icon" ]; then
        mkdir -p "$APPDIR"
        if [ "$_gui" = "1" ]; then _term=false; else _term=true; fi
        # An explicit title wins; the default is the app name, suffixed with the
        # launcher name when several entries would otherwise be indistinguishable.
        if [ -n "$_title" ]; then
            _entry_name=$_title
        elif [ "$_desktop_entries" -gt 1 ]; then
            _entry_name="$APP_NAME - $_name"
        else
            _entry_name="$APP_NAME"
        fi
        # Escape before interpolating: the prefix is arbitrary user input, so a
        # $, backtick, quote, or backslash in it would otherwise produce a
        # broken or misparsed entry (and an unquoted Icon path with spaces
        # misbehaves in some desktops).
        _d_name=$(desktop_string "$_entry_name")
        _d_exec=$(desktop_exec_arg "$LIBDIR/$_name")
        _d_icon=$(desktop_string "$LIBDIR/$_icon")
        cat > "$APPDIR/$DIST_NAME-$_name.desktop" <<EOF
[Desktop Entry]
Type=Application
Version=1.0
Name=$_d_name
Exec=$_d_exec %U
Icon=$_d_icon
Terminal=$_term
Categories=$CATEGORIES
EOF
    fi
done <<EOF
$LAUNCHERS
EOF

[ "$DESKTOP" = "1" ] && refresh_desktop_db

# Drop a standalone uninstaller with absolute paths baked in, so the user can
# remove the install later without the original .run file.
{
    echo "#!/bin/sh"
    echo "# Uninstall $APP_NAME (generated by pyappdist)"
    while IFS= read -r _entry; do
        [ -n "$_entry" ] || continue
        _name=${_entry%%:*}
        _rest=${_entry#*:}
        _icon=${_rest#*:}
        _icon=${_icon%%:*}
        echo "rm -f $(sq "$BINDIR/$_name")"
        if [ "$DESKTOP" = "1" ] && [ -n "$_icon" ]; then
            echo "rm -f $(sq "$APPDIR/$DIST_NAME-$_name.desktop")"
        fi
    done <<EOF
$LAUNCHERS
EOF
    echo "rm -rf $(sq "$LIBDIR")"
    if [ "$DESKTOP" = "1" ]; then
        echo "if command -v update-desktop-database >/dev/null 2>&1; then update-desktop-database $(sq "$APPDIR") >/dev/null 2>&1 || true; fi"
    fi
    echo "echo $(sq "Uninstalled $APP_NAME")"
} > "$LIBDIR/uninstall.sh"
chmod +x "$LIBDIR/uninstall.sh"

# Report the command(s) now available in BINDIR.
echo "Installed command(s) in $BINDIR:"
while IFS= read -r _name; do
    [ -n "$_name" ] || continue
    echo "  $_name"
done <<EOF
$_installed_cmds
EOF

case ":$PATH:" in
    *":$BINDIR:"*) ;;
    *) echo "note: $BINDIR is not on your PATH; add it to launch $APP_NAME by name" >&2 ;;
esac

echo "Installed $APP_NAME. Uninstall any time with: $LIBDIR/uninstall.sh"
exit 0
