# ---------------------------------------------------------------------------
# Static installer logic (generated by pyappdist; do not edit by hand).
#
# The lines above this block define:
#   APP_NAME DIST_NAME VERSION DESKTOP CATEGORIES LAUNCHERS DECOMPRESS PAYLOAD_SHA256 SELF
# LAUNCHERS is a whitespace-separated list of "name:gui:icon" records, where
# gui is 1/0 and icon is the bundled icon filename (empty = no desktop entry).
# DESKTOP is 1 on Linux (write freedesktop .desktop entries) and 0 on macOS,
# which has no freedesktop equivalent (symlinks only). DECOMPRESS is the filter
# that turns the payload back into a tar stream (e.g. "xz -dc"); PAYLOAD_SHA256
# is the expected checksum of the appended payload.
#
# A compressed tar of the image tree is appended after the marker line (see the
# awk pattern below) at the very end of this file.
# ---------------------------------------------------------------------------

PREFIX="${PREFIX:-$HOME/.local}"
DO_UNINSTALL=0

print_help() {
    cat <<EOF
$APP_NAME $VERSION installer

Usage: $0 [options]
  --prefix DIR    install prefix (default: \$HOME/.local)
  --uninstall     remove a previous installation
  -h, --help      show this help
EOF
}

while [ $# -gt 0 ]; do
    case "$1" in
        --prefix) PREFIX="$2"; shift 2 ;;
        --prefix=*) PREFIX="${1#--prefix=}"; shift ;;
        --uninstall) DO_UNINSTALL=1; shift ;;
        -h|--help) print_help; exit 0 ;;
        *) echo "error: unknown option: $1" >&2; exit 2 ;;
    esac
done

LIBDIR="$PREFIX/lib/$DIST_NAME"
BINDIR="$PREFIX/bin"
APPDIR="${XDG_DATA_HOME:-$HOME/.local/share}/applications"

refresh_desktop_db() {
    if command -v update-desktop-database >/dev/null 2>&1; then
        update-desktop-database "$APPDIR" >/dev/null 2>&1 || true
    fi
}

# Compute the SHA-256 of stdin, printing just the hex digest. Tries the common
# tools in turn; prints nothing if none is available (caller treats that as
# "cannot verify" rather than a failure). shasum covers macOS, sha256sum Linux.
sha256_of_stdin() {
    if command -v sha256sum >/dev/null 2>&1; then
        sha256sum | cut -d' ' -f1
    elif command -v shasum >/dev/null 2>&1; then
        shasum -a 256 | cut -d' ' -f1
    elif command -v openssl >/dev/null 2>&1; then
        openssl dgst -sha256 | sed 's/.*= *//'
    fi
}

# Remove a previous install. Placement is deterministic, so no manifest is needed.
remove_install() {
    for _entry in $LAUNCHERS; do
        _name=${_entry%%:*}
        _rest=${_entry#*:}
        _icon=${_rest#*:}
        rm -f "$BINDIR/$_name"
        if [ "$DESKTOP" = "1" ] && [ -n "$_icon" ]; then
            rm -f "$APPDIR/$DIST_NAME-$_name.desktop"
        fi
    done
    rm -rf "$LIBDIR"
    [ "$DESKTOP" = "1" ] && refresh_desktop_db
}

if [ "$DO_UNINSTALL" = "1" ]; then
    if [ ! -d "$LIBDIR" ]; then
        echo "error: $APP_NAME is not installed at $LIBDIR" >&2
        exit 1
    fi
    remove_install
    echo "Uninstalled $APP_NAME from $PREFIX"
    exit 0
fi

echo "Installing $APP_NAME $VERSION -> $LIBDIR"

# Locate the appended payload (the compressed tar after the marker line).
_payload_line=$(awk '/^__PYAPPDIST_PAYLOAD__$/ { print NR + 1; exit }' "$SELF")
if [ -z "$_payload_line" ]; then
    echo "error: payload marker not found in $SELF" >&2
    exit 1
fi

# Verify the payload checksum *before* removing any existing install, so a
# corrupted download can't leave the user with nothing.
_actual_sha=$(tail -n +"$_payload_line" "$SELF" | sha256_of_stdin)
if [ -z "$_actual_sha" ]; then
    echo "note: no sha256 tool found; skipping integrity check" >&2
elif [ "$_actual_sha" != "$PAYLOAD_SHA256" ]; then
    echo "error: payload checksum mismatch (file is corrupt or truncated)" >&2
    echo "  expected $PAYLOAD_SHA256" >&2
    echo "  actual   $_actual_sha" >&2
    exit 1
fi

remove_install            # clean any previous version (upgrade in place)
mkdir -p "$LIBDIR" "$BINDIR"

if ! tail -n +"$_payload_line" "$SELF" | $DECOMPRESS | tar xf - -C "$LIBDIR"; then
    echo "error: failed to extract payload" >&2
    exit 1
fi

# Symlink each launcher onto PATH and (on Linux, when it has an icon) register a .desktop.
_installed_cmds=""
for _entry in $LAUNCHERS; do
    _name=${_entry%%:*}
    _rest=${_entry#*:}
    _gui=${_rest%%:*}
    _icon=${_rest#*:}
    ln -sf "$LIBDIR/$_name" "$BINDIR/$_name"
    _installed_cmds="$_installed_cmds $_name"
    if [ "$DESKTOP" = "1" ] && [ -n "$_icon" ]; then
        mkdir -p "$APPDIR"
        if [ "$_gui" = "1" ]; then _term=false; else _term=true; fi
        cat > "$APPDIR/$DIST_NAME-$_name.desktop" <<EOF
[Desktop Entry]
Type=Application
Version=1.0
Name=$APP_NAME
Exec=$LIBDIR/$_name %U
Icon=$LIBDIR/$_icon
Terminal=$_term
Categories=$CATEGORIES
EOF
    fi
done

[ "$DESKTOP" = "1" ] && refresh_desktop_db

# Drop a standalone uninstaller with absolute paths baked in, so the user can
# remove the install later without the original .run file.
{
    echo "#!/bin/sh"
    echo "# Uninstall $APP_NAME (generated by pyappdist)"
    for _entry in $LAUNCHERS; do
        _name=${_entry%%:*}
        _rest=${_entry#*:}
        _icon=${_rest#*:}
        echo "rm -f \"$BINDIR/$_name\""
        if [ "$DESKTOP" = "1" ] && [ -n "$_icon" ]; then
            echo "rm -f \"$APPDIR/$DIST_NAME-$_name.desktop\""
        fi
    done
    echo "rm -rf \"$LIBDIR\""
    if [ "$DESKTOP" = "1" ]; then
        echo "if command -v update-desktop-database >/dev/null 2>&1; then update-desktop-database \"$APPDIR\" >/dev/null 2>&1 || true; fi"
    fi
    echo "echo \"Uninstalled $APP_NAME\""
} > "$LIBDIR/uninstall.sh"
chmod +x "$LIBDIR/uninstall.sh"

# Report the command(s) now available in BINDIR.
echo "Installed command(s) in $BINDIR:"
for _name in $_installed_cmds; do
    echo "  $_name"
done

case ":$PATH:" in
    *":$BINDIR:"*) ;;
    *) echo "note: $BINDIR is not on your PATH; add it to launch $APP_NAME by name" >&2 ;;
esac

echo "Installed $APP_NAME. Uninstall any time with: $LIBDIR/uninstall.sh"
exit 0
