"""Build the Linux deliverables from the image tree.

Two artifacts are produced for a ``format = "linux"`` target. Both use the
``compression`` chosen in ``[[tool.pyappdist.targets]]`` (``gzip`` / ``bzip2`` /
``xz``; default ``xz``):

* ``<name>-<version>-<target>.tar{.gz,.bz2,.xz}`` — the image tree under a top-level
  ``<name>-<version>/`` directory, for users who just want to extract and run.
* ``<name>-<version>-<target>.run`` — a self-extracting installer: a POSIX shell
  script (``resources/linux_installer.sh``) with a compressed tar of the image tree
  appended after a ``__PYAPPDIST_PAYLOAD__`` marker. The header carries the payload's
  SHA-256, which the installer verifies before extracting. Running it copies the tree into
  ``<prefix>/lib/<name>`` (``$HOME/.local`` by default), symlinks each launcher into
  ``<prefix>/bin``, and — only for launchers with an icon — writes a ``.desktop`` entry.

The launcher itself is a tiny relocatable shell wrapper (no MSVC, unlike Windows) that
locates the bundled interpreter relative to its own resolved path and runs the entry
point, so it works both from an extracted tarball and from the installed location.
"""

from __future__ import annotations

import hashlib
import io
import shutil
import tarfile
from pathlib import Path

from ..config import Config, LauncherConfig
from ..errors import BuildError
from ..image.layout import ImageLayout

_PAYLOAD_MARKER = b"__PYAPPDIST_PAYLOAD__\n"

# compression name -> (tarfile mode suffix, tarball extension, installer decompress command)
_COMPRESSION = {
    "gzip": ("gz", ".tar.gz", "gzip -dc"),
    "bzip2": ("bz2", ".tar.bz2", "bzip2 -dc"),
    "xz": ("xz", ".tar.xz", "xz -dc"),
}
_INSTALLER_BODY = (
    Path(__file__).resolve().parent.parent / "resources" / "linux_installer.sh"
).read_text(encoding="utf-8")


def build_linux(
    config: Config, layout: ImageLayout, dist_dir: Path, *, log=print
) -> list[Path] | None:
    """Build the .tar.gz and .run from the image. Returns None for non-Linux targets."""
    if config.target.os != "linux":
        log("linux: skipping because the target is not Linux")
        return None

    mode, ext, decompress = _COMPRESSION[config.linux.compression]

    image_dir = layout.image_dir
    records = _write_launchers(config, image_dir, log=log)
    launchers_field = " ".join(
        f"{name}:{1 if gui else 0}:{icon}" for (name, gui, icon) in records
    )

    dist_dir.mkdir(parents=True, exist_ok=True)
    base = f"{config.dist_name}-{config.version}-{config.target_name}"

    tarball = dist_dir / f"{base}{ext}"
    _make_tarball(image_dir, tarball, top=f"{config.dist_name}-{config.version}", mode=mode)
    log(f"linux: tarball -> {tarball}")

    run = dist_dir / f"{base}.run"
    payload = _targz_bytes(image_dir, mode=mode)
    sha256 = hashlib.sha256(payload).hexdigest()
    header = _render_header(config, launchers_field, decompress=decompress, sha256=sha256)
    run.write_bytes(
        header.encode("utf-8")
        + _INSTALLER_BODY.encode("utf-8")
        + _PAYLOAD_MARKER
        + payload
    )
    run.chmod(0o755)
    log(f"linux: installer -> {run} ({config.linux.compression}, sha256 {sha256[:12]}…)")
    return [tarball, run]


def _write_launchers(
    config: Config, image_dir: Path, *, log
) -> list[tuple[str, bool, str]]:
    """Write each launcher's shell wrapper (and stage its icon) into the image.

    Returns ``(name, gui, icon_filename)`` per launcher; ``icon_filename`` is empty
    when the launcher has no icon (then the installer writes no .desktop entry).
    """
    records: list[tuple[str, bool, str]] = []
    for spec in config.launchers:
        wrapper = image_dir / spec.name
        wrapper.write_text(_wrapper(spec), encoding="utf-8")
        wrapper.chmod(0o755)

        icon_name = ""
        if spec.icon:
            src = (config.project_dir / spec.icon).resolve()
            if not src.is_file():
                raise BuildError(f"launcher icon not found ({spec.name}): {src}")
            icon_name = f"{spec.name}{src.suffix}"
            shutil.copy2(src, image_dir / icon_name)
        records.append((spec.name, spec.gui, icon_name))
        log(f"linux: launcher {spec.name}" + (f" (+ icon {icon_name})" if icon_name else ""))
    return records


def _wrapper(spec: LauncherConfig) -> str:
    """A relocatable POSIX wrapper that runs the entry point via the bundled python."""
    module, _, func = spec.entry.partition(":")
    bootstrap = f"import sys; from {module} import {func}; sys.exit({func}())"
    args = spec.args.strip()
    extra = f" {args}" if args else ""  # appended verbatim (subject to word splitting)
    return (
        "#!/bin/sh\n"
        '# Generated by pyappdist. Locates the bundled interpreter relative to itself.\n'
        'HERE=$(CDPATH= cd -- "$(dirname -- "$(readlink -f -- "$0")")" && pwd)\n'
        f'exec "$HERE/python/bin/python3" -c {_sq(bootstrap)}{extra} "$@"\n'
    )


def _render_header(
    config: Config, launchers_field: str, *, decompress: str, sha256: str
) -> str:
    """The generated variable block prepended to the static installer body."""
    return (
        "#!/bin/sh\n"
        "# Self-extracting installer generated by pyappdist.\n"
        'SELF=$(readlink -f "$0" 2>/dev/null || echo "$0")\n'
        f"APP_NAME={_sq(config.name)}\n"
        f"DIST_NAME={_sq(config.dist_name)}\n"
        f"VERSION={_sq(config.version)}\n"
        f"CATEGORIES={_sq(config.linux.categories)}\n"
        f"LAUNCHERS={_sq(launchers_field)}\n"
        f"DECOMPRESS={_sq(decompress)}\n"
        f"PAYLOAD_SHA256={_sq(sha256)}\n"
    )


def _sq(s: str) -> str:
    """Quote a string as a single shell word (safe for arbitrary content)."""
    return "'" + s.replace("'", "'\\''") + "'"


def _targz_bytes(src_dir: Path, *, mode: str) -> bytes:
    """Compressed tar of the directory contents (no top-level dir), preserving symlinks."""
    buf = io.BytesIO()
    with tarfile.open(fileobj=buf, mode=f"w:{mode}") as tf:
        for child in sorted(src_dir.iterdir()):
            tf.add(child, arcname=child.name)
    return buf.getvalue()


def _make_tarball(src_dir: Path, out_path: Path, *, top: str, mode: str) -> None:
    """Compressed tar of the directory contents under a ``top/`` prefix, preserving symlinks."""
    with tarfile.open(out_path, f"w:{mode}") as tf:
        for child in sorted(src_dir.iterdir()):
            tf.add(child, arcname=f"{top}/{child.name}")
